### ISSUE TITLE
Design a data  structure [Priority]

### ISSUE THREAD

**Issue by Vlad-Vekslyer** [wadp413-January/midterm-team-b-1#1]
Design the data structure that will go into MongoDB. 
Once finished, share it in the github for us all to use and also update all of the existing routes to use your data structure. 
This needs to be completed ASAP

**Comment by mondai40** [comment]
[{
	"id": number,			//for editting, deleting, voting
	"data": number,
	"name": string,		//for name
	"title": string,			//for title
	"content": string,		//for blog main content
	"comment": [{			//for comment
		"date": number,
		"name": string, 
		"commentContent": string
	}],
	"like": number			//for vote
}]
